[package]
name = "ale_test"
version = "0.1.0"
authors = ["gmg137 <gmg137@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
